CREATE TABLE Page (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  path VARCHAR(100) UNIQUE NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  cache TEXT DEFAULT '',
  created DATETIME NOT NULL,
  modified DATETIME NOT NULL,
  param TEXT NOT NULL DEFAULT ''
);

CREATE TABLE Comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pageid INTEGER NOT NULL,
  name TEXT NOT NULL,
  body TEXT NOT NULL,
  created DATETIME NOT NULL
);

CREATE INDEX PagePath ON Page (path);
CREATE INDEX CommentPageID ON Comment (pageid);
